### ISSUE TITLE
[Bug]:requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

### ISSUE THREAD

**Issue by xiewenqian** [XiaoXinYo/Easy-Ernie#17]
### 在提交前请确保以下这些

- [X] easy-ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

MacOS

### Python版本

3.9

### 问题

requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

### 触发

Traceback (most recent call last):
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/PycharmProjects/Automate/main.py", line 318, in <module>
    do_combine(wf_combine, scene_offset)
  File "/Users/x/PycharmProjects/Automate/main.py", line 232, in do_combine
    asyncio.run(t_combine.execute(combine_dict))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/x/PycharmProjects/Automate/Workflow.py", line 34, in execute
    result = await current_task_instance.call_process(*args, **kwargs)
  File "/Users/x/PycharmProjects/Automate/TaskCombine.py", line 27, in call_process
    result = ernie.ask(combine_prompt, sessionName=session_name)
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/easy_ernie/ernie.py", line 332, in ask
    for data in self.askStream(question, sessionId, sessionName, parentChatId):
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/easy_ernie/ernie.py", line 282, in askStream
    for line in data.iter_lines():
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/Users/x/PycharmProjects/Automate/venv/lib/python3.9/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by XiaoXinYo** [comment]
方便告诉我` result = ernie.ask(combine_prompt, sessionName=session_name)`中的combine_prompt和session_name吗？

**Comment by xiewenqian** [comment]
combine_prompt 是一段800字左右的小说，让baidu仿写
session_name 我直接使用时间戳 比如：1704854918

**Comment by xiewenqian** [comment]
可能是我挂了代理的问题，去掉代理之后正常了
